### ISSUE TITLE
regression in input.py

### ISSUE THREAD

**Issue by vryadlapalli** [device-automation-bus/dab-compliance-suite#14]
When I run the latest compliance test, I'm getting these errors.
```
$:dab-compliance-testing-suite$ python3.9 main.py -v -I device0 -c 24

testing input/key/list   {} ... Traceback (most recent call last):
  File "/home/vyadlapalli/rokudev/apps_ndk_git/roku_dab/dab-compliance-testing-suite/main.py", line 182, in <module>
    Tester.Execute_Test_Case(device_id,(Test_Cases[args.case]))
  File "/home/vyadlapalli/rokudev/apps_ndk_git/roku_dab/dab-compliance-testing-suite/dab_tester.py", line 36, in Execute_Test_Case
    if validate_output_function(test_result, durationInMs, expected_response) == True:
  File "/home/vyadlapalli/rokudev/apps_ndk_git/roku_dab/dab-compliance-testing-suite/dab/input.py", line 59, in list
    KeyList.key_list = response.keyCodes
AttributeError: 'dict' object has no attribute 'keyCodes'
```
With this patch, I can run the test suite properly.

```
diff --git a/dab/input.py b/dab/input.py
index 80af45e..9a31f40 100644
--- a/dab/input.py
+++ b/dab/input.py
@@ -15,7 +15,7 @@ def key_press(test_result, durationInMs=0, expectedLatencyMs=None):
         if response['status'] != 200:
             return False
     else:
-        if request.keyCode in KeyList.key_list:
+        if request['keyCode'] in KeyList.key_list:
             if response['status'] != 200:
                 return False
         else:
@@ -36,7 +36,7 @@ def long_key_press(test_result, durationInMs=0, expectedLatencyMs=None):
         if response['status'] != 200:
             return False
     else:
-        if request.keyCode in KeyList.key_list:
+        if request['keyCode'] in KeyList.key_list:
             if response['status'] != 200:
                 return False
         else:
@@ -54,9 +54,9 @@ def list(test_result, durationInMs=0, expectedLatencyMs=0):
     response  = jsons.loads(test_result.response)
     if response['status'] != 200:
         return False
-    if len(response.keyCodes) <=0:
+    if len(response['keyCodes']) <=0:
         return False
-    KeyList.key_list = response.keyCodes
+    KeyList.key_list = response['keyCodes']
     sleep(0.1)
     return Default_Validations(test_result, durationInMs, expectedLatencyMs)
 

```

**Comment by bgy36ww** [comment]
Ah, I missed the error because my sdk has that returned as 501 instead of an actual list.

**Comment by bgy36ww** [comment]
Thanks for identify this!

**Comment by vryadlapalli** [comment]
Do we not need these two lines? These were required for input/key/list, as I understand.

+    if len(response['keyCodes']) <=0:
+    KeyList.key_list = response['keyCodes']

I will test with your latest change a little later and update the status.
