### ISSUE TITLE
paho-mqtt 2.0.0 not supported

### ISSUE THREAD

**Issue by asaka-xperi** [device-automation-bus/dab-compliance-suite#44]
The latest version of the paho-mqtt lib (2.0.0) is not supported. 

## Work around

`sed -i -e "s|paho-mqtt$|paho-mqtt==1.6.1|g" requirements.txt`

## Error
`````
Traceback (most recent call last):
  File "/home/asaka/dab/dab-compliance-suite/main.py", line 75, in <module>
    Tester = DabTester(args.broker)
  File "/home/asaka/dab/dab-compliance-suite/dab_tester.py", line 11, in __init__
    self.dab_client = DabClient()
  File "/home/asaka/dab/dab-compliance-suite/dab_client.py", line 12, in __init__
    self.__client = mqtt.Client("mqtt5_client",protocol=mqtt.MQTTv5)
  File "/home/asaka/.venv/override/lib/python3.10/site-packages/paho/mqtt/client.py", line 766, in __init__
    raise ValueError(
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details
`````

**Comment by hariprasad-hp** [comment]
requirements.txt (line 2) already pins

* paho-mqtt == 1.6.1

So the workaround mentioned in issue #44 has effectively already been applied.
The reported crash is consistent with paho-mqtt 2.0.0+, where callback API handling changed and old client construction can fail
